name: Generate DocC

# we'll start this action on every push to this branch
on:
  push:
    branches: [ docc ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: Git Checkout
    - uses: actions/checkout@v2
    - name: Build
    - run: |
          xcodebuild docbuild -scheme BinaryTree -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=latest'
    - name: Find DocC Archive
    - run: |
          find ./docbuild -type d -iname "BinaryTree.doccarchive"
