name: Generate DocC

# we'll start this action on every push to this branch
on:
  push:
    branches: [ main ]

jobs:
  Build-Github-Actions:
    runs-on: macos-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Build Doc Bundle
      run: |
          echo "🚀 Starting Job"
          # You can print out which version of Xcode is used in this GH Action
          # xcodebuild -version
          
          # Build documentation bundle
          xcodebuild docbuild -scheme BinaryTree -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 mini' > build_output.txt
          # I'm redirecting all output from building the project and docs to build_output.txt
          # If you want to see it, uncomment next line
          # cat build_output.txt
    - name: Find DooC Archive
      run: |
          echo "🚀 Starting Job"
          # This bundle is somewhere inside .docbuild, let's find it
          DOCC_DIR=`find ./docbuild -type d -iname "BinaryTree.doccarchive"`
          
          # let's move to that directory
          cd "$DOCC_DIR"
          cd ..
          ls -al
          
          
          git clone https://github.com/mongodb-developer/realm-binary-tree-docc
          cp -R BinaryTree.doccarchive realm-binary-tree-docc
          cd realm-binary-tree-docc
          git status
          git add .
          git commit -m "DocC generated from Action!"
          git status
          # git push origin
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: $DOCC_DIR
        destination-github-username: 'dfreniche'
        destination-repository-name: 'test'
        user-email: diego@freniche.com
        target-branch: main

    - run: echo "🍏 This job's status is ${{ job.status }}."
