name: Generate DocC

# we'll start this action on every push to this branch
on:
  push:
    branches: [ main ]

jobs:
  Build-Github-Actions:
    runs-on: macos-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Build Doc and Find Archive
      run: |
          echo "🚀 Starting Job"
          xcodebuild -version
          xcrun simctl list devices --json
          xcodebuild docbuild -scheme BinaryTree -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 mini'          
          find ./docbuild -type d -iname "BinaryTree.doccarchive"
    - run: echo "🍏 This job's status is ${{ job.status }}."
