name: Generate DocC

# we'll start this action on every push to this branch
on:
  push:
    branches: [ main ]

jobs:
  Build-Github-Actions:
    runs-on: macos-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Build Doc and Find Archive
      run: |
          echo "🚀 Starting Job"
          # You can print out which version of Xcode is used in this GH Action
          # xcodebuild -version
          
          # Build documentation bundle
          xcodebuild docbuild -scheme BinaryTree -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 mini'          
          
          # This bundle is somewhere inside .docbuild, let's find it
          DOCC_DIR=`find ./docbuild -type d -iname "BinaryTree.doccarchive"`
          
          # let's move to that directory
          cd "$DOCC_DIR"
          cd ..
          ls -al
    - run: echo "🍏 This job's status is ${{ job.status }}."
